language: ruby
rvm:
  - 2.3.1
services:
  - docker
install:
  - docker build -t e2eapp ruby-testapp
  - docker run -p 3000:3000 --name rubye2e e2eapp
script: docker ps


# before_install: gem install bundler -v 1.10.6
# install:
#   - bundle install
#    - bundle exec rake install
# script: "rake spec"
# after_success: "coveralls"
