#
#    Copyright 2018, Optimizely and contributors
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

url: "https://cdn.optimizely.com/json"

project_id: "10111011215"

experiments:
  sorting: "sorting_experiment"
  checkout_flow: "checkout_flow_experiment"

variations:
  sort_by_price: "sort_by_price"
  sort_by_price: "sort_by_name"
  one_step_checkout: "one_step_checkout"
  two_step_checkout: "two_step_checkout"

events:
  add_to_cart: "add_to_cart"
  checkout_complete: "checkout_complete"

features:
  buy_now_feature: "buynow_feature"
  discount_feature: "discount_feature"

feature_variables:
  discount_percentage: "discount_percentage"

