url: "https://cdn.optimizely.com/json"
project_id: "10111011215"
experiment_key: "sorting_experiment"
event_key: "add_to_cart"
buy_now_feature_flag: "buynow_feature"

discount_feature_flag: "discount_feature"
discount_feature_variable: "discount_percentage"

checkout_flow_experiment: "checkout_flow_experiment"
checkout_event_key: "checkout_complete"