# Gemfile
source 'https://rubygems.org'

gem 'rest-client', '~> 2.0', '>= 2.0.2'
gem 'sinatra'
# To use a ruby hash as a readonly datasource for an ActiveRecord-like model.
gem 'active_hash'
gem 'byebug'